
package Mantenimientos;


import Presentacion.MenuPrincipal;
import java.awt.Color;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author CRISTAL ORTEGA
 */
public class MantCatalogoDeCuenta extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MantCatalogoDeCuenta.class.getName());

  /*      private int nroCta;
    private String descripcion;
    private boolean tipoCta; 
    private int nivelCta;
    private int ctaPadre;
    private int grupoCta;
    private LocalDate fechaCreacion;
    private LocalTime horaCreacion;
    private double debitoAcum;
    private double creditoAcum;
    private double balance;
    
    
    /**
     * Creates new form MantCatalogoDeCuenta
     */
    public MantCatalogoDeCuenta() {
        initComponents();
        setLocationRelativeTo(null);
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Estado = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtNroCuenta = new javax.swing.JTextField();
        txtCuentaPadre = new javax.swing.JTextField();
        txtBalance = new javax.swing.JTextField();
        cmbTipo = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        cmbGrupo = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtHora = new javax.swing.JTextField();
        txtDebito = new javax.swing.JTextField();
        txtCredito = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        txtDescripcion = new javax.swing.JTextField();
        cmbNivel = new javax.swing.JComboBox<>();
        btnLimpiar3 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 600));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Estado.setFont(new java.awt.Font("Book Antiqua", 0, 12)); // NOI18N
        Estado.setOpaque(true);
        getContentPane().add(Estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 80, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(1010, 534));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setForeground(new java.awt.Color(204, 204, 255));
        jPanel2.setFont(new java.awt.Font("Constantia", 2, 14)); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Book Antiqua", 3, 24)); // NOI18N
        jLabel1.setText("Mantenimiento de catálogo");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1010, 50));

        jLabel3.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        jLabel3.setText("Cuenta padre");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, -1, -1));

        jLabel8.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        jLabel8.setText("Fecha de creacion");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 160, -1, -1));

        jLabel9.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        jLabel9.setText("Descripción");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, -1, -1));

        jLabel10.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        jLabel10.setText("Tipo de cuenta");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, -1, -1));

        jLabel11.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        jLabel11.setText("Nivel");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, -1, -1));

        txtNroCuenta.setFont(new java.awt.Font("Book Antiqua", 0, 12)); // NOI18N
        txtNroCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNroCuentaActionPerformed(evt);
            }
        });
        jPanel1.add(txtNroCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 140, -1));

        txtCuentaPadre.setFont(new java.awt.Font("Book Antiqua", 0, 12)); // NOI18N
        jPanel1.add(txtCuentaPadre, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, 140, -1));

        txtBalance.setEditable(false);
        txtBalance.setFont(new java.awt.Font("Book Antiqua", 0, 12)); // NOI18N
        jPanel1.add(txtBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 330, 100, -1));

        cmbTipo.setFont(new java.awt.Font("Book Antiqua", 0, 12)); // NOI18N
        cmbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "General", "Detalle", " ", " " }));
        jPanel1.add(cmbTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 140, -1));

        jLabel12.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        jLabel12.setText("Grupo");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 410, -1, -1));

        cmbGrupo.setFont(new java.awt.Font("Book Antiqua", 0, 12)); // NOI18N
        cmbGrupo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Pasivo", "Capital", "Ingresos", "Gastos", "Costos" }));
        jPanel1.add(cmbGrupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 410, 140, -1));

        jLabel13.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        jLabel13.setText("Balance");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 330, -1, -1));

        jLabel14.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        jLabel14.setText("Número de cuenta");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, -1, -1));

        txtFecha.setEditable(false);
        txtFecha.setFont(new java.awt.Font("Book Antiqua", 0, 12)); // NOI18N
        txtFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaActionPerformed(evt);
            }
        });
        jPanel1.add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 158, 120, -1));

        jLabel15.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        jLabel15.setText("Hora de creacion");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 190, -1, -1));

        jLabel16.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        jLabel16.setText("Debito acumulado");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 270, -1, -1));

        jLabel17.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        jLabel17.setText("Credito acumulado");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 300, -1, -1));

        txtHora.setEditable(false);
        txtHora.setFont(new java.awt.Font("Book Antiqua", 0, 12)); // NOI18N
        jPanel1.add(txtHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 190, 120, -1));

        txtDebito.setEditable(false);
        txtDebito.setFont(new java.awt.Font("Book Antiqua", 0, 12)); // NOI18N
        jPanel1.add(txtDebito, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 270, 100, -1));

        txtCredito.setEditable(false);
        txtCredito.setFont(new java.awt.Font("Book Antiqua", 0, 12)); // NOI18N
        jPanel1.add(txtCredito, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 300, 100, -1));

        btnGuardar.setBackground(java.awt.SystemColor.textHighlight);
        btnGuardar.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 490, 120, 44));

        btnModificar.setBackground(java.awt.SystemColor.activeCaptionBorder);
        btnModificar.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        btnModificar.setForeground(new java.awt.Color(255, 255, 255));
        btnModificar.setLabel("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jPanel1.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 490, 120, 44));

        btnEliminar.setBackground(new java.awt.Color(255, 0, 0));
        btnEliminar.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 490, 120, 44));

        txtDescripcion.setFont(new java.awt.Font("Book Antiqua", 0, 12)); // NOI18N
        jPanel1.add(txtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 140, -1));

        cmbNivel.setFont(new java.awt.Font("Book Antiqua", 0, 12)); // NOI18N
        cmbNivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", " " }));
        jPanel1.add(cmbNivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 310, 80, -1));

        btnLimpiar3.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        btnLimpiar3.setText("Limpiar");
        btnLimpiar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiar3ActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimpiar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 400, 120, 40));

        jPanel4.setBackground(new java.awt.Color(255, 189, 39));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setForeground(new java.awt.Color(204, 204, 255));
        jPanel4.setFont(new java.awt.Font("Constantia", 2, 14)); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1010, 10));

        btnSalir.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 490, 90, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1010, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
       MenuPrincipal MP=new MenuPrincipal();
       MP.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
   try {
    FileWriter fw = new FileWriter("CatalogoCuenta.txt", true);

    String fecha = LocalDate.now()
            .format(DateTimeFormatter.ofPattern("dd/MM/yyyy"));

    String hora = LocalTime.now()
            .format(DateTimeFormatter.ofPattern("HH:mm"));

    String linea =
            txtNroCuenta.getText() + "|" +
            txtDescripcion.getText() + "|" +
            cmbTipo.getSelectedItem() + "|" +
            cmbNivel.getSelectedItem() + "|" +
            txtCuentaPadre.getText() + "|" +
            cmbGrupo.getSelectedItem() + "|" +
            fecha + "|" +
            hora + "|" +
            "0|0|0";

    fw.write(linea + "\n");
    fw.close();

    JOptionPane.showMessageDialog(this,
            "Cuenta creada correctamente");
    limpiarCampos();

} catch (Exception e) {
    JOptionPane.showMessageDialog(this,
            "Error al guardar cuenta");
    }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
  ArrayList<String> lista = new ArrayList<>();

try {
    BufferedReader br = new BufferedReader(
            new FileReader("CatalogoCuenta.txt"));
    String linea;

    while ((linea = br.readLine()) != null) {
        String[] datos = linea.split("\\|");

        if (datos[0].equals(txtNroCuenta.getText())) {

            datos[1] = txtDescripcion.getText();
            datos[2] = cmbTipo.getSelectedItem().toString();
            datos[3] = cmbNivel.getSelectedItem().toString();
            datos[4] = txtCuentaPadre.getText();
            datos[5] = cmbGrupo.getSelectedItem().toString();

        }

        lista.add(String.join("|", datos));
    }
    br.close();

    FileWriter fw = new FileWriter("CatalogoCuenta.txt");
    for (String l : lista) {
        fw.write(l + "\n");
    }
    fw.close();

    JOptionPane.showMessageDialog(this,
            "Cuenta modificada correctamente");

    limpiarCampos();

} catch (Exception e) {
    JOptionPane.showMessageDialog(this,
            "Error al modificar cuenta");
        
}
    }//GEN-LAST:event_btnModificarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
         cargarFechaHora();
    }//GEN-LAST:event_formWindowOpened

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
      try {
    BufferedReader br = new BufferedReader(
            new FileReader("CatalogoCuenta.txt"));

    ArrayList<String> lista = new ArrayList<>();
    String linea;

    while ((linea = br.readLine()) != null) {
        String[] datos = linea.split("\\|");

        // si NO es la cuenta, se guarda
        if (!datos[0].equals(txtNroCuenta.getText())) {
            lista.add(linea);
        } else {
            // es la cuenta a eliminar
      double debito = Double.parseDouble(datos[8]);
double credito = Double.parseDouble(datos[9]);
String tipoCuenta = datos[2]; // General o Detalle

if (tipoCuenta.equals("Detalle") && (debito != 0 || credito != 0)) {
    JOptionPane.showMessageDialog(this,
            "No se puede eliminar, la cuenta tiene movimientos");
    br.close();
    return;
}
            // si llega aquí, se elimina (no se guarda)
        }
    }

    br.close();

    FileWriter fw = new FileWriter("CatalogoCuenta.txt");
    for (String l : lista) {
        fw.write(l + "\n");
    }
    fw.close();

    JOptionPane.showMessageDialog(this,
            "Cuenta eliminada correctamente");
    limpiarCampos();

} catch (Exception e) {
    JOptionPane.showMessageDialog(this,
            "Error al eliminar cuenta");
}
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txtFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaActionPerformed

    private void btnLimpiar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiar3ActionPerformed
      limpiarCampos();
    }//GEN-LAST:event_btnLimpiar3ActionPerformed

    private void txtNroCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNroCuentaActionPerformed
       String cuentaBuscada = txtNroCuenta.getText().trim();
    if (cuentaBuscada.isEmpty()) return;

    File archivo = new File("CatalogoCuenta.txt");
    if (!archivo.exists()) return;

    try (BufferedReader br = new BufferedReader(new FileReader(archivo))) {

        String linea;
        boolean encontrado = false;

        while ((linea = br.readLine()) != null) {
            String[] datos = linea.split("\\|");

            if (datos.length >= 11 && datos[0].equals(cuentaBuscada)) {

                txtDescripcion.setText(datos[1]);
                cmbTipo.setSelectedItem(datos[2]);
                cmbNivel.setSelectedItem(datos[3]);
                txtCuentaPadre.setText(datos[4]);
                cmbGrupo.setSelectedItem(datos[5]);
                txtFecha.setText(datos[6]);
                txtHora.setText(datos[7]);
                txtDebito.setText(datos[8]);
                txtCredito.setText(datos[9]);
                txtBalance.setText(datos[10]);

                encontrado = true;
                break;
            }
        }

        // si no existe, limpiar (como en usuario)
        if (!encontrado) {
            txtDescripcion.setText("");
            cmbTipo.setSelectedIndex(0);
            cmbNivel.setSelectedIndex(0);
            txtCuentaPadre.setText("");
            cmbGrupo.setSelectedIndex(0);
            txtDebito.setText("0");
            txtCredito.setText("0");
            txtBalance.setText("0");
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this,
                "Error al buscar la cuenta");
    }
    }//GEN-LAST:event_txtNroCuentaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MantCatalogoDeCuenta().setVisible(true));
    }
    
    
    private void limpiarCampos() {
    txtNroCuenta.setText("");
    txtDescripcion.setText("");
    cmbTipo.setSelectedIndex(0);
    cmbTipo.setSelectedIndex(0);
    txtCuentaPadre.setText("");
    cmbGrupo.setSelectedIndex(0);
    txtDebito.setText("0");
    txtCredito.setText("0");
    txtBalance.setText("0");
  
}

    private void cargarFechaHora() {

    DateTimeFormatter fFecha =
            DateTimeFormatter.ofPattern("dd/MM/yyyy");

    DateTimeFormatter fHora =
            DateTimeFormatter.ofPattern("HH:mm");

    txtFecha.setText(
            LocalDate.now().format(fFecha));

    txtHora.setText(
            LocalTime.now().format(fHora));

    txtFecha.setEnabled(false);
    txtHora.setEnabled(false);
}
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Estado;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar3;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cmbGrupo;
    private javax.swing.JComboBox<String> cmbNivel;
    private javax.swing.JComboBox<String> cmbTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField txtBalance;
    private javax.swing.JTextField txtCredito;
    private javax.swing.JTextField txtCuentaPadre;
    private javax.swing.JTextField txtDebito;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtHora;
    private javax.swing.JTextField txtNroCuenta;
    // End of variables declaration//GEN-END:variables
}
