/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Mantenimientos;

import Presentacion.MenuPrincipal;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author CRISTAL ORTEGA
 */


public class MantUsuario extends javax.swing.JFrame {
     int nivelTemp;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MantUsuario.class.getName());

    /**
     * Creates new form MantUsuario
     */
    public MantUsuario() {
        initComponents();
      setLocationRelativeTo(null);
      
      
}
    
    public void nivel(){
       
          
          if(txtNivelAcceso.getSelectedItem().toString().equals("Normal")) {
    nivelTemp = 1;
} else {
    nivelTemp = 0;
}
    }
    
private File getArchivoUsuarios() throws Exception {
    File archivo = new File("Usuarios.txt");

  
    if (!archivo.exists()) {
        archivo.createNewFile();
    }

    return archivo;
}
        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        txtUsuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtContraseña = new javax.swing.JPasswordField();
        MostrarContraseña = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        txtNivelAcceso = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnSalir = new javax.swing.JButton();
        Estado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMaximumSize(new java.awt.Dimension(1010, 600));
        jPanel2.setMinimumSize(new java.awt.Dimension(1010, 600));
        jPanel2.setPreferredSize(new java.awt.Dimension(1010, 600));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUsuario.setFont(new java.awt.Font("Book Antiqua", 0, 12)); // NOI18N
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        jPanel2.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 146, -1));

        jLabel2.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        jLabel2.setText("Usuario");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, -1, -1));

        txtNombre.setFont(new java.awt.Font("Book Antiqua", 0, 12)); // NOI18N
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        jPanel2.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 146, -1));

        jLabel5.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        jLabel5.setText("Nombre");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, -1, -1));

        txtApellido.setFont(new java.awt.Font("Book Antiqua", 0, 12)); // NOI18N
        txtApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoActionPerformed(evt);
            }
        });
        jPanel2.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 146, -1));

        jLabel6.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        jLabel6.setText("Apellido");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, -1, -1));

        txtCorreo.setFont(new java.awt.Font("Book Antiqua", 0, 12)); // NOI18N
        txtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoActionPerformed(evt);
            }
        });
        jPanel2.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 340, 146, -1));

        jLabel7.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        jLabel7.setText("Correo");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, -1, -1));

        txtContraseña.setFont(new java.awt.Font("Book Antiqua", 0, 12)); // NOI18N
        jPanel2.add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 140, 120, -1));

        MostrarContraseña.setFont(new java.awt.Font("Book Antiqua", 1, 10)); // NOI18N
        MostrarContraseña.setText("Mostrar contraseña");
        MostrarContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarContraseñaActionPerformed(evt);
            }
        });
        jPanel2.add(MostrarContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 170, 130, 20));

        jLabel3.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        jLabel3.setText("Contraseña");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 120, -1, -1));

        txtNivelAcceso.setFont(new java.awt.Font("Book Antiqua", 0, 12)); // NOI18N
        txtNivelAcceso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Normal", "Administrador" }));
        txtNivelAcceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNivelAccesoActionPerformed(evt);
            }
        });
        jPanel2.add(txtNivelAcceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 230, 120, -1));

        jLabel4.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        jLabel4.setText("Nivel de acceso");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 210, -1, -1));

        btnEliminar.setBackground(new java.awt.Color(255, 0, 0));
        btnEliminar.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel2.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 450, 120, 44));

        btnModificar.setBackground(java.awt.SystemColor.controlShadow);
        btnModificar.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        btnModificar.setForeground(new java.awt.Color(255, 255, 255));
        btnModificar.setLabel("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jPanel2.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 450, 120, 44));

        btnGuardar.setBackground(java.awt.SystemColor.textHighlight);
        btnGuardar.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel2.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 450, 120, 44));

        btnLimpiar.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        jPanel2.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 320, -1, 40));

        jPanel3.setBackground(new java.awt.Color(153, 204, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setForeground(new java.awt.Color(204, 204, 255));
        jPanel3.setFont(new java.awt.Font("Constantia", 2, 14)); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Book Antiqua", 3, 24)); // NOI18N
        jLabel1.setText("Mantenimiento de usuario");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 50));

        jPanel4.setBackground(new java.awt.Color(255, 189, 39));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setForeground(new java.awt.Color(204, 204, 255));
        jPanel4.setFont(new java.awt.Font("Constantia", 2, 14)); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1010, 10));

        btnSalir.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel2.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 450, 90, 40));

        Estado.setFont(new java.awt.Font("Constantia", 3, 12)); // NOI18N
        Estado.setText("jLabel8");
        Estado.setToolTipText("");
        jPanel2.add(Estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 90, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
          txtContraseña.requestFocus();
    }//GEN-LAST:event_txtCorreoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
     
        int nivelTemp;
        if(txtNivelAcceso.getSelectedItem().toString().equals("Normal")){
            nivelTemp=1;
        }
        else{
            nivelTemp=0;
        }
        if (txtUsuario.getText().trim().isEmpty() || txtContraseña.getText().trim().isEmpty() || txtCorreo.getText().trim().isEmpty() || txtApellido.getText().trim().isEmpty() || txtNombre.getText().trim().isEmpty()) {
    JOptionPane.showMessageDialog(this, "Complete todos los campos");
    return;
}
        
        
        try {
        File archivo = getArchivoUsuarios();

        Scanner leer = new Scanner(archivo);
        String usuarioIngresado = txtUsuario.getText().trim();
 //aqui para identificar si existe un usuario con el mismo nombre,
        while (leer.hasNextLine()) {
            String linea = leer.nextLine();
            String[] d = linea.split(";");
            if (d[0].equalsIgnoreCase(usuarioIngresado)) {
                leer.close();
                JOptionPane.showMessageDialog(this, "El nombre de usuario ya existe, ingrese otro.");
                return;
            }
        }
        leer.close();

        FileWriter fw = new FileWriter(archivo, true);

        
        nivel();
        fw.write(
            txtUsuario.getText() + ";" +
            txtContraseña.getText() + ";" +
            nivelTemp + ";" +
            txtNombre.getText() + ";" +
            txtApellido.getText() + ";" +
            txtCorreo.getText() + "\n"
        );
       

        fw.close();
        JOptionPane.showMessageDialog(this, "Usuario guardado correctamente.");
        limpiarCampos();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al guardar: " + e.getMessage());
    }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
    String usuarioBuscado = txtUsuario.getText();

    File archivo = new File("Usuarios.txt");
    File archivoTemp = new File("Usuarios_temp.txt");

    try {
        BufferedReader br = new BufferedReader(new FileReader(archivo));
        BufferedWriter bw = new BufferedWriter(new FileWriter(archivoTemp));

        String linea;
        boolean encontrado = false;

        while ((linea = br.readLine()) != null) {

            String[] datos = linea.split(";");
nivel();
           
            if (datos[0].equals(usuarioBuscado)) {
                String nuevaLinea = txtUsuario.getText() + ";" +
                                    txtContraseña.getText() + ";" +
                                    nivelTemp + ";" +
                                    txtNombre.getText() + ";" +
                                    txtApellido.getText() + ";" +
                                    txtCorreo.getText();

                bw.write(nuevaLinea);
                encontrado = true;

            } else {
                // dejamos la línea igual
                bw.write(linea);
            }

            bw.newLine();
        }

        br.close();
        bw.close();

       // para reemplazar archivo viejo por el nuevo  y renombrar el nuevo a archivo
        archivo.delete();
        archivoTemp.renameTo(archivo);

        if (encontrado) {
            JOptionPane.showMessageDialog(this, "Usuario modificado.");
            limpiarCampos();
        } else {
            JOptionPane.showMessageDialog(this, "Usuario no encontrado.");
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
       try {
        File archivo = getArchivoUsuarios();
        File temp = new File("TempUsuarios.txt");

        Scanner sc = new Scanner(archivo);
        BufferedWriter bw = new BufferedWriter(new FileWriter(temp));

        boolean eliminado = false;

        while (sc.hasNextLine()) {
            String linea = sc.nextLine();
            String[] d = linea.split(";");

            if (d[0].equals(txtUsuario.getText())) {
                eliminado = true;
                continue; 
            }

            bw.write(linea);
            bw.newLine();
        }

        sc.close();
        bw.close();

        archivo.delete();
        temp.renameTo(archivo);

        if (eliminado) {
            JOptionPane.showMessageDialog(this, "Usuario eliminado.");
            limpiarCampos();
        } else {
            JOptionPane.showMessageDialog(this, "Usuario no encontrado.");
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al eliminar ");
    }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
limpiarCampos();  
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
      txtNombre.requestFocus();
      String usuarioBuscado = txtUsuario.getText().trim();
    if (usuarioBuscado.isEmpty()) return;

    File archivo = new File("Usuarios.txt");

 
    if (!archivo.exists()) {
        return;
    }

    try (BufferedReader br = new BufferedReader(new FileReader(archivo))) {
        String linea;
        boolean encontrado = false;

        while ((linea = br.readLine()) != null) {
            String[] datos = linea.split(";");

            if (datos.length == 6 && datos[0].equals(usuarioBuscado)) {
                txtContraseña.setText(datos[1]);
                txtNivelAcceso.setSelectedItem(datos[2]);
                txtNombre.setText(datos[3]);
                txtApellido.setText(datos[4]);
                txtCorreo.setText(datos[5]);

                encontrado = true;
                break;
            }
        }

      
        if (!encontrado) {
            txtContraseña.setText("");
            txtNivelAcceso.setSelectedIndex(0);
            txtNombre.setText("");
            txtApellido.setText("");
            txtCorreo.setText("");
        }

    } catch (Exception e) {
     
        
    }
      
      
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        txtApellido.requestFocus();
        if(txtUsuario.getText()==null){
              JOptionPane.showMessageDialog(this, "Debe llenar el campo");
        }
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoActionPerformed
        txtCorreo.requestFocus();
    }//GEN-LAST:event_txtApellidoActionPerformed

    private void txtNivelAccesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNivelAccesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNivelAccesoActionPerformed

    private void MostrarContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarContraseñaActionPerformed
        if (MostrarContraseña.isSelected()) {
            txtContraseña.setEchoChar((char) 0); // Muestra la contraseña
        } else {
            txtContraseña.setEchoChar('•'); // Oculta la contraseña (puedes usar '*')
        }
    }//GEN-LAST:event_MostrarContraseñaActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
      MenuPrincipal MP=new MenuPrincipal();
      MP.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MantUsuario().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Estado;
    private javax.swing.JCheckBox MostrarContraseña;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JPasswordField txtContraseña;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JComboBox<String> txtNivelAcceso;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables

    private void limpiarCampos() {
           txtUsuario.setText("");
    txtNombre.setText("");
    txtContraseña.setText("");
    txtApellido.setText("");
    txtCorreo.setText("");
    txtNivelAcceso.setSelectedIndex(0); 
    }

 
}
