/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Movimientos;

import Presentacion.MenuPrincipal;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author CRISTAL ORTEGA
 */
public class Transacciones extends javax.swing.JFrame {
    
    private boolean cabeceraExiste = false;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Transacciones.class.getName());

    /**
     * Creates new form Transacciones
     */
    public Transacciones() {
        initComponents();
        setLocationRelativeTo(null);
          DefaultTableModel modelo = (DefaultTableModel) tblDetalle2.getModel();
    modelo.setRowCount(0);
            txtNroDocu.addKeyListener(new java.awt.event.KeyAdapter() {
           
        });
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        CabeceraTransaccionContable = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbTipoDocu = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtNroDocu = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        txtMonto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        DetalleTransaccion = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtCredito = new javax.swing.JTextField();
        txtDebito = new javax.swing.JTextField();
        txtDescripcionCuenta = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        txtNumCuenta = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblDetalle2 = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        txtTotalCredito = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtTotalDebito = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtBalance = new javax.swing.JTextField();
        btnSalir = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(1010, 600));
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMaximumSize(new java.awt.Dimension(1010, 600));
        jPanel2.setMinimumSize(new java.awt.Dimension(1010, 600));
        jPanel2.setPreferredSize(new java.awt.Dimension(1010, 600));

        CabeceraTransaccionContable.setBackground(new java.awt.Color(255, 255, 255));
        CabeceraTransaccionContable.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        jLabel1.setText("Fecha");
        CabeceraTransaccionContable.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        jLabel2.setText("Tipo de documento");
        CabeceraTransaccionContable.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        cmbTipoDocu.setFont(new java.awt.Font("Book Antiqua", 0, 12)); // NOI18N
        cmbTipoDocu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Factura", "Ajuste", "Documento Interno", "Nota de Débito", "Nota de Crédito" }));
        CabeceraTransaccionContable.add(cmbTipoDocu, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 150, -1));

        jLabel3.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        jLabel3.setText("No. Documento");
        CabeceraTransaccionContable.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        txtNroDocu.setFont(new java.awt.Font("Book Antiqua", 0, 12)); // NOI18N
        txtNroDocu.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNroDocuFocusLost(evt);
            }
        });
        txtNroDocu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNroDocuActionPerformed(evt);
            }
        });
        txtNroDocu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNroDocuKeyReleased(evt);
            }
        });
        CabeceraTransaccionContable.add(txtNroDocu, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 100, -1));

        txtFecha.setEditable(false);
        txtFecha.setFont(new java.awt.Font("Book Antiqua", 0, 12)); // NOI18N
        CabeceraTransaccionContable.add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 20, 130, -1));

        txtMonto.setEditable(false);
        txtMonto.setFont(new java.awt.Font("Book Antiqua", 0, 12)); // NOI18N
        CabeceraTransaccionContable.add(txtMonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 50, 130, -1));

        jLabel4.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        jLabel4.setText("Monto");
        CabeceraTransaccionContable.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 50, -1, -1));

        DetalleTransaccion.setBackground(new java.awt.Color(255, 255, 255));
        DetalleTransaccion.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        DetalleTransaccion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        jLabel5.setText("Descripción");
        DetalleTransaccion.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel6.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        jLabel6.setText("Descripción");
        DetalleTransaccion.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, -1));

        jLabel7.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        jLabel7.setText("Crédito");
        DetalleTransaccion.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, -1, -1));

        jLabel8.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        jLabel8.setText("Débito");
        jLabel8.setToolTipText("");
        DetalleTransaccion.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 40, -1, -1));

        txtCredito.setFont(new java.awt.Font("Book Antiqua", 0, 12)); // NOI18N
        txtCredito.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCreditoKeyReleased(evt);
            }
        });
        DetalleTransaccion.add(txtCredito, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, 120, -1));

        txtDebito.setFont(new java.awt.Font("Book Antiqua", 0, 12)); // NOI18N
        txtDebito.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDebitoKeyReleased(evt);
            }
        });
        DetalleTransaccion.add(txtDebito, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 60, 110, -1));

        txtDescripcionCuenta.setFont(new java.awt.Font("Book Antiqua", 0, 12)); // NOI18N
        DetalleTransaccion.add(txtDescripcionCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 190, -1));

        btnAgregar.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(102, 204, 0));
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        DetalleTransaccion.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 81, 34));

        btnEliminar.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 0, 0));
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        DetalleTransaccion.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, -1, 34));

        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        jScrollPane6.setViewportView(txtDescripcion);

        DetalleTransaccion.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 220, 60));

        jLabel13.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        jLabel13.setText("No. Cuenta");
        DetalleTransaccion.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        txtNumCuenta.setFont(new java.awt.Font("Book Antiqua", 0, 12)); // NOI18N
        txtNumCuenta.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNumCuentaFocusLost(evt);
            }
        });
        txtNumCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumCuentaActionPerformed(evt);
            }
        });
        DetalleTransaccion.add(txtNumCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 100, -1));

        tblDetalle2.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        tblDetalle2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "No. Cuenta", "Descripción cuenta", "Descripción", "Débito", "Crédito"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblDetalle2);

        jLabel10.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        jLabel10.setText("Total crédito");

        txtTotalCredito.setEditable(false);
        txtTotalCredito.setFont(new java.awt.Font("Book Antiqua", 0, 12)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        jLabel9.setText("Total debito");

        txtTotalDebito.setEditable(false);
        txtTotalDebito.setFont(new java.awt.Font("Book Antiqua", 0, 12)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        jLabel11.setText("Balance");

        txtBalance.setEditable(false);
        txtBalance.setFont(new java.awt.Font("Book Antiqua", 0, 12)); // NOI18N

        btnSalir.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(153, 204, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setForeground(new java.awt.Color(204, 204, 255));
        jPanel4.setFont(new java.awt.Font("Constantia", 2, 14)); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Book Antiqua", 3, 24)); // NOI18N
        jLabel12.setText("Movimiento de transacciones");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        jPanel5.setBackground(new java.awt.Color(255, 189, 39));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.setForeground(new java.awt.Color(204, 204, 255));
        jPanel5.setFont(new java.awt.Font("Constantia", 2, 14)); // NOI18N
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnGuardar.setBackground(java.awt.SystemColor.textHighlight);
        btnGuardar.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CabeceraTransaccionContable, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DetalleTransaccion, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(txtTotalCredito, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(104, 104, 104)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(txtTotalDebito, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(101, 101, 101)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(txtBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(84, 84, 84)
                                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 885, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 1010, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 1010, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(CabeceraTransaccionContable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DetalleTransaccion, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTotalCredito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTotalDebito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1010, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
       MenuPrincipal MP=new MenuPrincipal();
       MP.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
   int fila = tblDetalle2.getSelectedRow();

        if (fila == -1) {
            JOptionPane.showMessageDialog(this,
                    "Seleccione una fila para eliminar");
            return;
        }

        DefaultTableModel modelo = (DefaultTableModel) tblDetalle2.getModel();
        modelo.removeRow(fila);
        calcularTotales();  
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
  if (txtNroDocu.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                    "Debe ingresar el número de documento primero");
            txtNroDocu.requestFocus();
            return;
        }

        if (txtNumCuenta.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                    "Ingrese el número de cuenta");
            txtNumCuenta.requestFocus();
            return;
        }

        if (txtDebito.getText().trim().isEmpty() && 
            txtCredito.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                    "Debe ingresar débito o crédito");
            return;
        }

        if (!txtDebito.getText().trim().isEmpty() && 
            !txtCredito.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                    "Solo puede ingresar débito O crédito, no ambos");
            return;
        }

        // Validar que sea una cuenta válida y de detalle
        if (!validarCuenta()) {
            return;
        }

        // Validar que los valores sean numéricos
        try {
            if (!txtDebito.getText().trim().isEmpty()) {
                Double.parseDouble(txtDebito.getText().trim());
            }
            if (!txtCredito.getText().trim().isEmpty()) {
                Double.parseDouble(txtCredito.getText().trim());
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, 
                    "Débito y crédito deben ser valores numéricos");
            return;
        }

        // Agregar a la tabla
        agregarFila();
        limpiarDetalle();
        calcularTotales();
        txtNumCuenta.requestFocus();
        txtNumCuenta.setText("");

    }//GEN-LAST:event_btnAgregarActionPerformed

   private boolean validarCuenta() {
        try {
            BufferedReader br = new BufferedReader(
                    new FileReader("CatalogoCuenta.txt"));
            String linea;

            while ((linea = br.readLine()) != null) {
                String[] datos = linea.split("\\|");

                // Verificar que la cuenta existe
                if (datos[0].equals(txtNumCuenta.getText())) {
                    
                    // Verificar que sea de tipo Detalle
                    if (!datos[2].equalsIgnoreCase("Detalle")) {
                        JOptionPane.showMessageDialog(this,
                                "La cuenta debe ser de tipo Detalle");
                        br.close();
                        return false;
                    }

                    // Cargar la descripción de la cuenta
                    txtDescripcionCuenta.setText(datos[1]);
                    br.close();
                    return true;
                }
            }

            br.close();
            JOptionPane.showMessageDialog(this, 
                    "La cuenta no existe en el catálogo");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Error al leer el catálogo de cuentas: " + e.getMessage());
        }

        return false;
    
}
  private void agregarFila() {
     DefaultTableModel modelo = (DefaultTableModel) tblDetalle2.getModel();

        String debito = txtDebito.getText().isEmpty() ? "0" : txtDebito.getText();
        String credito = txtCredito.getText().isEmpty() ? "0" : txtCredito.getText();

        // Agregar al final de la tabla (de arriba hacia abajo)
        modelo.addRow(new Object[]{
            txtNumCuenta.getText(),
            txtDescripcionCuenta.getText(),
            txtDescripcion.getText(),
            debito,
            credito
        });
        
        // Hacer scroll automático a la última fila agregada
        int ultimaFila = tblDetalle2.getRowCount() - 1;
        tblDetalle2.setRowSelectionInterval(ultimaFila, ultimaFila);
        tblDetalle2.scrollRectToVisible(
                tblDetalle2.getCellRect(ultimaFila, 0, true));
}
    
   private void limpiarDetalle() {
    txtDescripcionCuenta.setText("");
    txtDescripcion.setText("");
    txtDebito.setText("");
    txtCredito.setText("");
      txtDebito.setEnabled(true);
    txtCredito.setEnabled(true);
} 
    
    private void txtNroDocuFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNroDocuFocusLost
     
    cabeceraExiste = false;

    try {
        BufferedReader br = new BufferedReader(
                new FileReader("CabeceraTransaccionContable.txt"));
        String linea;

        while ((linea = br.readLine()) != null) {
            String[] datos = linea.split("\\|");

            if (datos[0].equals(txtNroDocu.getText())) {

                cabeceraExiste = true;

                if (datos[5].equals("ACTUALIZADA")) {
                    JOptionPane.showMessageDialog(this,
                            "La transacción ya fue actualizada");
                    br.close();
                    return;
                } else {
                    cargarCabecera(datos);
                    br.close();
                    return;
                }
            }
        }

        br.close();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error leyendo cabecera");
    }
    }//GEN-LAST:event_txtNroDocuFocusLost

    private void txtCreditoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCreditoKeyReleased
        if (txtCredito.getText().isEmpty()) {
        txtDebito.setEnabled(true);
    } else {
        txtDebito.setEnabled(false);
    }
        
    }//GEN-LAST:event_txtCreditoKeyReleased

    private void txtDebitoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDebitoKeyReleased
       if (txtDebito.getText().isEmpty()) {
        txtCredito.setEnabled(true);
    } else {
        txtCredito.setEnabled(false);
    }
        
    }//GEN-LAST:event_txtDebitoKeyReleased

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
  if (txtNroDocu.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Debe ingresar el número de documento");
            return;
        }


        if (tblDetalle2.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this,
                    "Debe agregar al menos un detalle");
            return;
        }

        double totalDebito = 0;
        double totalCredito = 0;

        for (int i = 0; i < tblDetalle2.getRowCount(); i++) {
           totalDebito += Double.parseDouble(tblDetalle2.getValueAt(i, 3).toString());
totalCredito += Double.parseDouble(tblDetalle2.getValueAt(i, 4).toString());
        }

        if (totalDebito == 0 || totalCredito == 0) {
            JOptionPane.showMessageDialog(this,
                    "Debe existir al menos un débito y un crédito");
            return;
        }

        if (Math.abs(totalDebito - totalCredito) > 0.01) {
            JOptionPane.showMessageDialog(this,
                    "Los débitos y créditos deben ser iguales");
            return;
        }

        try {
            // Guardar cabecera solo si no existe
            if (!cabeceraExiste) {
                FileWriter fwCab = new FileWriter(
                        "CabeceraTransaccionContable.txt", true);
                String descripcionCabecera =
        tblDetalle2.getValueAt(0, 2).toString();

                fwCab.write(
                       txtNroDocu.getText() + "|" +
                       txtFecha.getText() + "|" +
                       cmbTipoDocu.getSelectedItem().toString() + "|" +
                       descripcionCabecera + "|" +
                       txtMonto.getText() + "|" +
                       "PENDIENTE"
                );
                fwCab.close();
            } else {
                // Si la cabecera existe, primero eliminar los detalles anteriores
                eliminarDetallesAnteriores(txtNroDocu.getText());
            }

            // Guardar detalles
            FileWriter fwDet = new FileWriter("Transaccion.txt", true);

            for (int i = 0; i < tblDetalle2.getRowCount(); i++) {
                fwDet.write(
                        txtNroDocu.getText() + "|" +
    tblDetalle2.getValueAt(i, 0) + "|" +
    tblDetalle2.getValueAt(i, 1) + "|" +
    tblDetalle2.getValueAt(i, 2) + "|" +
    tblDetalle2.getValueAt(i, 3) + "|" +
    tblDetalle2.getValueAt(i, 4) + "\n"
                );
            }

            fwDet.close();

            // Actualizar catálogo y estado
            actualizarCatalogoCuenta();
            actualizarEstadoCabecera();

            JOptionPane.showMessageDialog(this,
                    "Transacción guardada correctamente");

            limpiarCampos();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Error al guardar la transacción: " + e.getMessage());
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
      cargarFecha();
     
    }//GEN-LAST:event_formWindowOpened

    private void txtNumCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumCuentaActionPerformed
       
    }//GEN-LAST:event_txtNumCuentaActionPerformed

    private void txtNroDocuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNroDocuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNroDocuActionPerformed

    private void txtNroDocuKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNroDocuKeyReleased
         // Si el campo de número de documento está vacío y hay detalles agregados
        if (txtNroDocu.getText().trim().isEmpty() && tblDetalle2.getRowCount() > 0) {
            // Preguntar si desea cancelar
            SwingUtilities.invokeLater(() -> {
                int respuesta = JOptionPane.showConfirmDialog(this,"Al borrar el número de documento se cancelará la transacción." +
                        "¿Desea continuar?",
                        "Cancelar transacción",
                        JOptionPane.YES_NO_OPTION,
                        JOptionPane.WARNING_MESSAGE);
                
                if (respuesta == JOptionPane.YES_OPTION) {
                    limpiarCampos();
                }
            });
        }
    }//GEN-LAST:event_txtNroDocuKeyReleased

    private void txtNumCuentaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNumCuentaFocusLost
           if (!txtNumCuenta.getText().trim().isEmpty()) {
        validarCuenta();
           }
    }//GEN-LAST:event_txtNumCuentaFocusLost

    public void limpiarCampos(){
          txtNroDocu.setText("");
        txtDescripcion.setText("");
        txtMonto.setText("");
        txtTotalDebito.setText("");
        txtTotalCredito.setText("");
        txtBalance.setText("");
        txtNumCuenta.setText("");
        txtDescripcionCuenta.setText("");
        txtDebito.setText("");
        txtCredito.setText("");
     
        cabeceraExiste = false;

        DefaultTableModel modelo = (DefaultTableModel) tblDetalle2.getModel();
        modelo.setRowCount(0);
    }

    private void calcularTotales() {
  double totalDebito = 0;
        double totalCredito = 0;

        for (int i = 0; i < tblDetalle2.getRowCount(); i++) {
           double debito = Double.parseDouble(tblDetalle2.getValueAt(i, 3).toString());
double credito = Double.parseDouble(tblDetalle2.getValueAt(i, 4).toString());

            totalDebito += debito;
            totalCredito += credito;
        }

        txtTotalDebito.setText(String.format("%.2f", totalDebito));
        txtTotalCredito.setText(String.format("%.2f", totalCredito));
        txtBalance.setText(String.format("%.2f", totalDebito - totalCredito));
        txtMonto.setText(String.format("%.2f", totalDebito));
    
    
}
    
    
    private void cargarCabecera(String[] datos) {
    cmbTipoDocu.setSelectedItem(datos[2]);
        txtFecha.setText(datos[1]);
        txtDescripcion.setText(datos[3]);
        txtMonto.setText(datos[4]);
        
        // Cargar los detalles existentes
        cargarDetalles(txtNroDocu.getText());
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Transacciones().setVisible(true));
    }
    private void cargarDetalles(String nroDocumento) {
        try {
            BufferedReader br = new BufferedReader(new FileReader("Detalle.txt"));
            String linea;
            DefaultTableModel modelo = (DefaultTableModel) tblDetalle2.getModel();
            modelo.setRowCount(0); // Limpiar tabla

            while ((linea = br.readLine()) != null) {
                String[] datos = linea.split("\\|");
                
                // datos[0] = No. Documento
                if (datos[0].equals(nroDocumento)) {
                    modelo.addRow(new Object[]{
                          datos[1], // No. Cuenta
                          datos[2], // Descripción cuenta
                          datos[3], // Descripción
                          datos[4], // Débito
                          datos[5]  // Crédito
                    });
                }
            }
            
            br.close();
            calcularTotales();
            
        } catch (Exception e) {
            // Si no existe el archivo o está vacío, no hay problema
        }
    }
    
      private void eliminarDetallesAnteriores(String nroDocumento) {
        try {
            BufferedReader lector = new BufferedReader(
                    new FileReader("Detalle.txt"));
            FileWriter escritor = new FileWriter("DetalleTemp.txt");

            String linea;

            while ((linea = lector.readLine()) != null) {
                String[] datos = linea.split("\\|");
                
                // Solo copiar si NO es del documento actual
                if (!datos[0].equals(nroDocumento)) {
                    escritor.write(linea + "\n");
                }
            }

            lector.close();
            escritor.close();

            File archivoOriginal = new File("Detalle.txt");
            File archivoTemp = new File("DetalleTemp.txt");
            
            archivoOriginal.delete();
            archivoTemp.renameTo(archivoOriginal);

        } catch (Exception e) {
            // Si no existe el archivo, no hay problema
        }
    }
      private void cargarFecha() {

    DateTimeFormatter fFecha =
            DateTimeFormatter.ofPattern("dd/MM/yyyy");
    txtFecha.setText(
            LocalDate.now().format(fFecha));

  
    txtFecha.setEnabled(false);

    
}
      
      
      
      
      
     private void actualizarCatalogoCuenta() {
        try {
            BufferedReader lector = new BufferedReader(
                    new FileReader("CatalogoCuenta.txt"));
            FileWriter escritor = new FileWriter("CatalogoTemp.txt");

            String linea;

            while ((linea = lector.readLine()) != null) {
                String[] datos = linea.split("\\|");
                String numeroCuenta = datos[0];

                double debito = Double.parseDouble(datos[8]);
                double credito = Double.parseDouble(datos[9]);

                // Buscar si esta cuenta está en la transacción
                for (int i = 0; i < tblDetalle2.getRowCount(); i++) {
                    if (numeroCuenta.equals(
                            tblDetalle2.getValueAt(i, 0).toString())) {

                        debito += Double.parseDouble(
                              tblDetalle2.getValueAt(i, 3) .toString());
                        credito += Double.parseDouble(
                                tblDetalle2.getValueAt(i, 4).toString());
                    }
                }

                double balance = debito - credito;

                // Actualizar los valores
                datos[8] = String.format("%.2f", debito);
                datos[9] = String.format("%.2f", credito);
                datos[10] = String.format("%.2f", balance);

                // Escribir la línea actualizada
                escritor.write(String.join("|", datos) + "\n");
            }

            lector.close();
            escritor.close();

            // Reemplazar archivo original
            File archivoOriginal = new File("CatalogoCuenta.txt");
            File archivoTemp = new File("CatalogoTemp.txt");
            
            archivoOriginal.delete();
            archivoTemp.renameTo(archivoOriginal);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Error al actualizar el catálogo: " + e.getMessage());
        }
   
}
   private void actualizarEstadoCabecera() {
        try {
            BufferedReader lector = new BufferedReader(
                    new FileReader("CabeceraTransaccionContable.txt"));
            FileWriter escritor = new FileWriter("CabeceraTemp.txt");

            String linea;

            while ((linea = lector.readLine()) != null) {
                String[] datos = linea.split("\\|");

                if (datos[0].equals(txtNroDocu.getText())) {
                    datos[5] = "ACTUALIZADA";
                }

                escritor.write(String.join("|", datos) + "\n");
            }

            lector.close();
            escritor.close();

            File archivoOriginal = new File("CabeceraTransaccionContable.txt");
            File archivoTemp = new File("CabeceraTemp.txt");
            
            archivoOriginal.delete();
            archivoTemp.renameTo(archivoOriginal);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Error al actualizar estado de cabecera: " + e.getMessage());
        }

}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CabeceraTransaccionContable;
    private javax.swing.JPanel DetalleTransaccion;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cmbTipoDocu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable tblDetalle2;
    private javax.swing.JTextField txtBalance;
    private javax.swing.JTextField txtCredito;
    private javax.swing.JTextField txtDebito;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtDescripcionCuenta;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtMonto;
    private javax.swing.JTextField txtNroDocu;
    private javax.swing.JTextField txtNumCuenta;
    private javax.swing.JTextField txtTotalCredito;
    private javax.swing.JTextField txtTotalDebito;
    // End of variables declaration//GEN-END:variables
}
